import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductsService {
  products = [
    {
      id:'1',
      ImgSrc:'figurines/asterix-1.jpeg',
      price:'99 ',
      personnage:'Astérix',
      dimensions:'22 x 11 x 6 cm',
      height:'700g',
      matiere:'la résine',
    },
    {
      id:'2',
      ImgSrc:'figurines/obelix-2.jpeg',
      price:'85',
      personnage:'Obélix',
      dimensions:'20 x 13 x 8 cm',
      height:'900g',
      matiere:'la résine',
    },
    {
      id:'3',
      ImgSrc:'figurines/idefix-3.jpeg',
      price:'75',
      personnage:'Idéfix',
      dimensions:'7 x 11 x 8 cm',
      height:'780g',
      matiere:'la résine',
    },
    {
      id:'4',
      ImgSrc:'figurines/panoramix-4.jpeg',
      price:'45',
      personnage:'Panoramix',
      dimensions:'12 x 7 x 6 cm',
      height:'680g',
      matiere:'la résine',
    },
    {
      id:'5',
      ImgSrc:'figurines/abraracourcix-5.jpeg',
      price:'55',
      personnage:'Abraracourcix',
      dimensions:'15 x 9 x 6 cm',
      height:'700g',
      matiere:'la résine',
    },
    {
      id:'6',
      ImgSrc:'figurines/assurancetourix-6.jpeg',
      price:'75',
      personnage:'Assurancetourix',
      dimensions:'22 x 11 x 8 cm',
      height:'500g',
      matiere:'la résine',
    },
    {
      id:'7',
      ImgSrc:'figurines/falbala-7.jpeg',
      price:'65',
      personnage:'Falbala',
      dimensions:'18 x 10 x 7 cm',
      height:'550g',
      matiere:'la polyéthylène',
    },
    {
      id:'8',
      ImgSrc:'figurines/obelix-8.jpeg',
      price:'79',
      personnage:'Obélix',
      dimensions:'17 x 13 x 8 cm',
      height:'500g',
      matiere:'la résine',
    },
    {
      id:'9',
      ImgSrc:'figurines/obelix-9.jpeg',
      price:'99',
      personnage:'Obélix',
      dimensions:'20 x 11 x 10 cm',
      height:'600g',
      matiere:'la polyéthylène',
    },
    {
      id:'10',
      ImgSrc:'figurines/abraracourcix-10.jpeg',
      price:'45',
      personnage:'Abraracourcix',
      dimensions:'16 x 7 x 5 cm',
      height:'800g',
      matiere:"l'alliage",
    },
    {
      id:'11',
      ImgSrc:'figurines/abraracourcix-11.jpeg',
      price:'65',
      personnage:'Abraracourcix',
      dimensions:'13 x 7 x 6 cm',
      height:'650g',
      matiere:'la polyéthylène',
    },
    {
      id:'12',
      ImgSrc:'figurines/panoramix-12.jpeg',
      price:'55',
      personnage:'Panoramix',
      dimensions:'17 x 9 x 7cm',
      height:'600g',
      matiere:'la résine',
    },
    {
      id:'13',
      ImgSrc:'figurines/panoramix-13.jpeg',
      price:'65',
      personnage:'Panoramix',
      dimensions:'17 x 9 x 7cm',
      height:'470g',
      matiere:'la résine',
    },
    {
      id:'14',
      ImgSrc:'figurines/panoramix-14.jpeg',
      price:'59',
      personnage:'Panoramix',
      dimensions:'13 x 7 x 6 cm',
      height:'500g',
      matiere:'la polyéthylène',
    },
    {
      id:'15',
      ImgSrc:'figurines/panoramix-15.jpeg',
      price:'49',
      personnage:'Panoramix',
      dimensions:'17 x 9 x 7cm',
      height:'500g',
      matiere:'la résine',
    },
    {
      id:'16',
      ImgSrc:'figurines/assurancetourix-16.jpeg',
      price:'69',
      personnage:'Assurancetourix',
      dimensions:'17 x 9 x 7cm',
      height:'750g',
      matiere:"l'alliage", 
    },
    {
      id:'17',
      ImgSrc:'figurines/assurancetourix-17.jpeg',
      price:'79',
      personnage:'Assurancetourix',
      dimensions:'13 x 7 x 6 cm',
      height:'600g',
      matiere:'la résine',
    }
  ]

  constructor() { }
}
